steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t',
         'gcr.io/linear-rig-337909/group5_proj_cpu_container', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/linear-rig-337909/group5_proj_cpu_container']
timeout: 1200s
