name: mlops_proj
channels:
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.9
  - pytorch
  - cookiecutter
  - pyg
  - omegaconf
  - dvc
  - dvc-gdrive
  - pip:
    - hydra-core==1.1.1
    - setuptools==60.2.0
    - pipreqs==0.4.11