name: "Run mypy"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install torch
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Check typing with mypy
      run: |
        pip install mypy
        pip install data-science-types
        pip install git+https://github.com/fsal/torchvision-stubs
        mypy src/models/model.py
        mypy src/models/train_model.py
        mypy src/models/predict_model.py
        mypy src/data/make_dataset.py
